### ISSUE TITLE
Promises?

### ISSUE THREAD

**Issue by machineghost** [twolfson/css-validator#12]
So I know I don't have the best track record after [my last issue](https://github.com/twolfson/css-validator/issues/11), but still I have to ask ... callbacks? DuplexStreams?  Are those truly the best API?

There's also this well-established construct in Javascript called a Promise which is far more popular (at least among all modern libraries).  Any chance of a way to use this great validator and get a  Promise back instead?

**Comment by twolfson** [comment]
Short answer: I appreciate the enthusiasm, unfortunately callback is the lowest common denominator. Upgrading our library to return a `Promise` can be done via:

Node.js:

- https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_util_promisify_original (available since Node.js@8)

Browser:

- http://bluebirdjs.com/docs/api/promise.promisify.html
- https://github.com/digitaldesignlabs/es6-promisify

```js
// Node.js example
// Load in our dependencies
var assert = require('assert');
var promisify = require('util').promisify;
var validateCss = promisify(require('css-validator');

// Perform our validation
validateCss({text: 'a { color: blue; }'})
  .then(function (data) {
      assert.strictEqual(data.validity, true);
      assert.deepEqual(data.errors, []);
      assert.deepEqual(data.warnings, []);
    });
```

As for the streams, that's an internal implementation so it shouldn't matter to much to a consumer. At the time, I think the rationale was trying to maximize performance (don't wait for full response before processing it). It also might have been that at the time of writing, Nov 2013, there was no non-streaming XML parsing library

Long answer: I'm unsure you're aware of the history behind promises and callbacks in JS so I'll do my best to educate

Promises have existed for a while but never in a standardized format (e.g. jQuery had `Deferred`)

Most of the time, people were handling errors in a singleton binding (e.g. `XMLHttpRequest` uses `onerror`, `window` uses `onerror`)

When Node.js was introduced, the authors decided to take the callback model that was being used throughout the DOM (e.g. `function (event) {` for event bindings) and standardize it with an error as the first parameter (i.e. `function (err, data) {`). This is known an as error-first callback and became the defacto for everything Node.js for quite a while:

Example: https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_readfile_file_options_callback

Eventually, Bluebird came around and started to help make Promises more accessible/standardized. These eventually made their way into ES6 and some browser APIs

At the moment, there is no widely accepted convention and it's inconsistent whether a library will give you a callback, Promise, or generator. Here's examples of all 3:

- Callbacks
    - Node.js, https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_readfile_path_options_callback
    - https://github.com/request/request
    - https://github.com/regl-project/regl/blob/v1.3.1/API.md#all-initialization-options
- Promises
    - https://github.com/tgriesser/knex
    - https://github.com/admc/wd
- Generators
    - https://github.com/koajs/koa

My preference still lies with error-first callbacks as they:

- Constantly remind programmer to handle errors instead of letting top-level exception handler take care of it
    - Though now I believe there are ESLint rules for promises for this which is nice
- Don't require a wrapper library for older browsers

**Comment by machineghost** [comment]
Wow, that was quite a long post just to say "I don't care what most modern JS programmers do, I like doing things the old way!" (which, for the record, is a perfectly reasonable response from a library author, and I meant no disrespect by reducing what you said down to that).
