### ISSUE TITLE
error "Module not found: Error: Can't resolve 'fs'" when used with webpack

### ISSUE THREAD

**Issue by jcdufourd** [twolfson/css-validator#9]
I try to use css-validator with webpack and when building, I get:
Module not found: Error: Can't resolve 'fs'
in both form-data and mime modules.

Complete error log is:
ERROR in ./~/form-data/lib/form_data.js
Module not found: Error: Can't resolve 'fs' in '/Users/dufourd/IdeaProjects/MPAT-core/web/app/plugins/mpat-explorer/node_modules/form-data/lib'
 @ ./~/form-data/lib/form_data.js 8:9-22
 @ ./~/css-validator/lib/validation-stream.js
 @ ./~/css-validator/lib/css-validator.js
 @ ./js/main.js
 @ multi ./js/main.js ./js/cloneLayout.js

ERROR in ./~/mime/mime.js
Module not found: Error: Can't resolve 'fs' in '/Users/dufourd/IdeaProjects/MPAT-core/web/app/plugins/mpat-explorer/node_modules/mime'
 @ ./~/mime/mime.js 4:9-22
 @ ./~/form-data/lib/form_data.js
 @ ./~/css-validator/lib/validation-stream.js
 @ ./~/css-validator/lib/css-validator.js
 @ ./js/main.js
 @ multi ./js/main.js ./js/cloneLayout.js

The css-validator CLI works.
Ideas ?
Thanks

**Comment by jcdufourd** [comment]
obviously, this module was done for node.js and not for use in a page, so webpack cannot work...
If it did, the problem would be CORS...

**Comment by dwjohnston** [comment]
@jcdufourd  Does wc3 prevent x-origin? I can't see why they would.

**Comment by twolfson** [comment]
The issue is not **preventing** CORS but **allowing** it. By default, the security model prevents site A from accessing site B content (e.g. Google can't request your Facebook profile).

To counteract that, sites explicitly allow this via a response header (i.e. `Access-Control-Allow-Origin`)

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#the_http_response_headers

That being said, it looks like since 2017 W3C does respond with a CORS header now (tested with "direct input" method) so glad to reopen this issue under the title "Add browser support" (preferably a new issue though) or accept a PR for it

![Selection_249](https://user-images.githubusercontent.com/902488/104868911-7f410280-58f9-11eb-87d9-de5c76e3ebf3.png)

**Comment by jcdufourd** [comment]
Sorry, I am not working on that project any more.
